### ISSUE TITLE
Unable to use the PacketData value and unit

### ISSUE THREAD

**Issue by Amartya-Mahato** [Kyome22/SystemInfoKit#3]
![Screenshot 2024-04-19 at 11 42 41 AM](https://github.com/Kyome22/SystemInfoKit/assets/72689903/a701a1ae-2f76-45d2-a9b5-d0b845647c1e)

not able to use unit and value directly from Packetdata?

**Comment by Kyome22** [comment]
@Amartya-Mahato 
Thank you for requesting.
I changed the access levels of PacketData value & unit.
You can use ver 3.2.0.
